AWSTemplateFormatVersion: 2010-09-09
Description: Merlindomx IAM Stack v1.2.0
Parameters: {}
Mappings: {}
Metadata: {}
Conditions: {}
Resources:
  MerlindomxCodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonRDSFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonVPCReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AWSElasticBeanstalkFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonRoute53FullAccess'
        - 'arn:aws:iam::aws:policy/AWSLambdaFullAccess'
      Path: /
      Policies:
        - PolicyName: !Join
            - ''
            - - MerlindomxCodePipelineEc2InstancePolicy
              - !Ref 'AWS::StackName'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'codedeploy:CreateDeployment'
                  - 'codedeploy:GetApplicationRevision'
                  - 'codedeploy:GetDeployment'
                  - 'codedeploy:GetDeploymentConfig'
                  - 'codedeploy:RegisterApplicationRevision'
                  - 'elasticloadbalancing:DescribeInstanceHealth'
                  - 'elasticloadbalancing:DescribeLoadBalancers'
                  - 'elasticloadbalancing:DescribeTargetHealth'
                  - 'autoscaling:DescribeAutoScalingGroups'
                  - 'autoscaling:DescribeLaunchConfigurations'
                  - 'autoscaling:DescribeScalingActivities'
                  - 'autoscaling:ResumeProcesses'
                  - 'autoscaling:SuspendProcesses'
                  - 'elasticloadbalancing:DescribeLoadBalancers'
                  - 'sns:ListSubscriptionsByTopic'
                  - 'sqs:GetQueueAttributes'
                  - 'sqs:GetQueueUrl'
                  - 'autoscaling:DescribeAutoScalingGroups'
                  - 'autoscaling:DescribeAutoScalingInstances'
                  - 'autoscaling:DescribeScalingActivities'
                  - 'autoscaling:DescribeNotificationConfigurations'
                  - 'cloudformation:GetTemplate'
                  - 'cloudformation:DescribeStackResource'
                  - 'cloudformation:DescribeStackResources'
                  - 'cloudformation:DescribeStackEvents'
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:UpdateStack'
                  - 'cloudformation:CreateChangeSet'
                  - 'cloudformation:DeleteChangeSet'
                  - 'cloudformation:DescribeChangeSet'
                  - 'cloudformation:ExecuteChangeSet'
                  - 'cloudformation:SetStackPolicy'
                  - 'cloudformation:ValidateTemplate'
                  - 'iam:PassRole'
                Resource:
                  - '*'
              - Action:
                  - 's3:Get*'
                  - 's3:List*'
                  - 's3:PutObject'
                Effect: Allow
                Resource:
                  - 'arn:aws:s3:::Merlindomx-stratalux-*'
                  - 'arn:aws:s3:::Merlindomx-stratalux-*/*'
                  - 'arn:aws:s3:::elasticbeanstalk-*'
                  - 'arn:aws:s3:::elasticbeanstalk-*/*'
              - Action:
                  - 's3:PutObject'
                Resource:
                  - 'arn:aws:s3:::codepipeline*'
                  - 'arn:aws:s3:::elasticbeanstalk*'
                Effect: Allow
  MerlindomxCodePipelineCFRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonRDSFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonVPCReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AWSElasticBeanstalkFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonRoute53FullAccess'
        - 'arn:aws:iam::aws:policy/AWSLambdaFullAccess'
      Path: /
      Policies:
        - PolicyName: !Join
            - ''
            - - MerlindomxCodePipelineEc2InstancePolicy
              - !Ref 'AWS::StackName'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'codedeploy:CreateDeployment'
                  - 'codedeploy:GetApplicationRevision'
                  - 'codedeploy:GetDeployment'
                  - 'codedeploy:GetDeploymentConfig'
                  - 'codedeploy:RegisterApplicationRevision'
                  - 'elasticloadbalancing:DescribeInstanceHealth'
                  - 'elasticloadbalancing:DescribeLoadBalancers'
                  - 'elasticloadbalancing:DescribeTargetHealth'
                  - 'autoscaling:DescribeAutoScalingGroups'
                  - 'autoscaling:DescribeLaunchConfigurations'
                  - 'autoscaling:DescribeScalingActivities'
                  - 'autoscaling:ResumeProcesses'
                  - 'autoscaling:SuspendProcesses'
                  - 'elasticloadbalancing:DescribeLoadBalancers'
                  - 'sns:ListSubscriptionsByTopic'
                  - 'sqs:GetQueueAttributes'
                  - 'sqs:GetQueueUrl'
                  - 'autoscaling:DescribeAutoScalingGroups'
                  - 'autoscaling:DescribeAutoScalingInstances'
                  - 'autoscaling:DescribeScalingActivities'
                  - 'autoscaling:DescribeNotificationConfigurations'
                  - 'cloudformation:GetTemplate'
                  - 'cloudformation:DescribeStackResource'
                  - 'cloudformation:DescribeStackResources'
                  - 'cloudformation:DescribeStackEvents'
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:UpdateStack'
                  - 'cloudformation:CreateChangeSet'
                  - 'cloudformation:DeleteChangeSet'
                  - 'cloudformation:DescribeChangeSet'
                  - 'cloudformation:ExecuteChangeSet'
                  - 'cloudformation:SetStackPolicy'
                  - 'cloudformation:ValidateTemplate'
                  - 'codepipeline:UpdatePipeline'
                  - 'codepipeline:CreatePipeline'
                  - 'codepipeline:DeletePipeline'
                  - 'codepipeline:GetPipeline'
                  - 'codepipeline:GetPipelineState'
                  - 'codedeploy:*'
                  - 'iam:PassRole'
                Resource:
                  - '*'
              - Action:
                  - 's3:Get*'
                  - 's3:List*'
                  - 's3:PutObject'
                Effect: Allow
                Resource:
                  - 'arn:aws:s3:::Merlindomx-stratalux-*'
                  - 'arn:aws:s3:::Merlindomx-stratalux-*/*'
                  - 'arn:aws:s3:::elasticbeanstalk-*'
                  - 'arn:aws:s3:::elasticbeanstalk-*/*'
              - Action:
                  - 's3:PutObject'
                Resource:
                  - 'arn:aws:s3:::codepipeline*'
                  - 'arn:aws:s3:::elasticbeanstalk*'
                Effect: Allow
  MerlindomxLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonVPCFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AWSCodePipelineFullAccess'
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'
      Path: /
      Policies: []
  MerlindomxInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
                - elasticbeanstalk.amazonaws.com
                - codedeploy.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonRDSFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonVPCReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AWSElasticBeanstalkFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSSMFullAccess'
      Path: /
      Policies:
        - PolicyName: !Join
            - ''
            - - MerlindomxEc2InstancePolicy
              - !Ref 'AWS::StackName'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 's3:Get*'
                  - 's3:List*'
                  - 's3:PutObject'
                Effect: Allow
                Resource:
                  - 'arn:aws:s3:::Merlindomx-stratalux-*'
                  - 'arn:aws:s3:::Merlindomx-stratalux-*/*'
                  - 'arn:aws:s3:::elasticbeanstalk-*'
                  - 'arn:aws:s3:::elasticbeanstalk-*/*'
              - Action:
                  - 'cloudwatch:PutMetricData'
                Effect: Allow
                Resource: '*'
              - Action:
                  - 'sqs:ChangeMessageVisibility'
                  - 'sqs:DeleteMessage'
                  - 'sqs:ReceiveMessage'
                  - 'sqs:SendMessage'
                Effect: Allow
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'ecs:Poll'
                  - 'ecs:StartTask'
                  - 'ecs:StopTask'
                  - 'ecs:DiscoverPollEndpoint'
                  - 'ecs:StartTelemetrySession'
                  - 'ecs:RegisterContainerInstance'
                  - 'ecs:DeregisterContainerInstance'
                  - 'ecs:DescribeContainerInstances'
                  - 'ecs:Submit*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'logs:PutLogEvents'
                  - 'logs:CreateLogStream'
                  - 'logs:DescribeLogStreams'
                  - 'logs:DescribeLogGroups'
                Resource:
                  - 'arn:aws:logs:*:*:log-group:/aws/elasticbeanstalk*'
              - Effect: Allow
                Action:
                  - 'elasticloadbalancing:DescribeInstanceHealth'
                  - 'elasticloadbalancing:DescribeLoadBalancers'
                  - 'elasticloadbalancing:DescribeTargetHealth'
                  - 'ec2:DescribeInstances'
                  - 'ec2:DescribeInstanceStatus'
                  - 'ec2:GetConsoleOutput'
                  - 'ec2:AssociateAddress'
                  - 'ec2:DescribeAddresses'
                  - 'ec2:DescribeSecurityGroups'
                  - 'sqs:GetQueueAttributes'
                  - 'sqs:GetQueueUrl'
                  - 'autoscaling:DescribeAutoScalingGroups'
                  - 'autoscaling:DescribeAutoScalingInstances'
                  - 'autoscaling:DescribeScalingActivities'
                  - 'autoscaling:DescribeNotificationConfigurations'
                Resource:
                  - '*'
  MerlindomxInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref MerlindomxInstanceRole
Outputs:
  MerlindomxInstanceProfile:
    Description: Merlindomx Instance Profile
    Value: !Ref MerlindomxInstanceProfile
    Export:
      Name: !Sub '${AWS::StackName}-MerlindomxInstanceProfile'
  MerlindomxInstanceRoleArn:
    Description: Merlindomx Instance Role ARN
    Value: !GetAtt
      - MerlindomxInstanceRole
      - Arn
    Export:
      Name: !Sub '${AWS::StackName}-MerlindomxInstanceRoleArn'
  MerlindomxInstanceRole:
    Description: Merlindomx Instance Role
    Value: !Ref MerlindomxInstanceRole
    Export:
      Name: !Sub '${AWS::StackName}-MerlindomxInstanceRole'
  MerlindomxCodePipelineRoleArn:
    Description: Merlindomx CodePipeline Role ARN
    Value: !GetAtt
      - MerlindomxCodePipelineRole
      - Arn
    Export:
      Name: !Sub '${AWS::StackName}-MerlindomxCodePipelineRoleArn'
  MerlindomxCodePipelineCFRoleArn:
    Description: Merlindomx CodePipeline CF Role ARN
    Value: !GetAtt
      - MerlindomxCodePipelineCFRole
      - Arn
    Export:
      Name: !Sub '${AWS::StackName}-MerlindomxCodePipelineCFRoleArn'
  MerlindomxLambdaRoleArn:
    Description: Merlindomx Lambda Role ARN
    Value: !GetAtt
      - MerlindomxLambdaRole
      - Arn
    Export:
      Name: !Sub '${AWS::StackName}-MerlindomxLambdaRoleArn'
